"""empty message

Revision ID: 0246a6ab8ce7
Revises: 5125fe93800a
Create Date: 2017-12-01 01:11:54.608900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0246a6ab8ce7'
down_revision = '5125fe93800a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AddressBook', sa.Column('stripe_account', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AddressBook', 'stripe_account')
    # ### end Alembic commands ###
