"""empty message

Revision ID: 150671bccd67
Revises: b3127e128619
Create Date: 2017-10-24 21:01:08.857678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150671bccd67'
down_revision = 'b3127e128619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bet_id'], ['Bets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Likes')
    # ### end Alembic commands ###
