"""empty message

Revision ID: 19e9d7f221ac
Revises: 86bc8cf819c8
Create Date: 2017-11-21 17:33:58.206226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e9d7f221ac'
down_revision = '86bc8cf819c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BetUsers', sa.Column('confirmed', sa.Integer(), nullable=False))
    op.add_column('Users', sa.Column('loses', sa.Integer(), nullable=True))
    op.add_column('Users', sa.Column('wins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'wins')
    op.drop_column('Users', 'loses')
    op.drop_column('BetUsers', 'confirmed')
    # ### end Alembic commands ###
