"""empty message

Revision ID: 1b206605542d
Revises: 266b0524718d
Create Date: 2017-11-19 15:44:59.258549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b206605542d'
down_revision = '266b0524718d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bets', sa.Column('creation_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bets', 'creation_time')
    # ### end Alembic commands ###
