"""empty message

Revision ID: 2aa2b672dd1d
Revises: ae4f765e3cbd
Create Date: 2017-10-29 17:42:53.680932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa2b672dd1d'
down_revision = 'ae4f765e3cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BetUsers', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('Bets', sa.Column('pot', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bets', 'pot')
    op.drop_column('BetUsers', 'active')
    # ### end Alembic commands ###
