"""empty message

Revision ID: 34536256de86
Revises: 7e82e3d99e31
Create Date: 2017-11-29 21:08:04.597470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34536256de86'
down_revision = '7e82e3d99e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('user_to', sa.Integer(), nullable=False),
    sa.Column('user_from', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_from'], ['Users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_to'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Friends')
    # ### end Alembic commands ###
