"""empty message

Revision ID: 704fd8217b00
Revises: fbc74473bbb7
Create Date: 2017-11-29 14:15:57.102897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704fd8217b00'
down_revision = 'fbc74473bbb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('BetUsers_ibfk_1', 'BetUsers', type_='foreignkey')
    op.create_foreign_key(None, 'BetUsers', 'Bets', ['bet_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('Transactions_ibfk_2', 'Transactions', type_='foreignkey')
    op.create_foreign_key(None, 'Transactions', 'Bets', ['bet_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Transactions', type_='foreignkey')
    op.create_foreign_key('Transactions_ibfk_2', 'Transactions', 'Bets', ['bet_id'], ['id'])
    op.drop_constraint(None, 'BetUsers', type_='foreignkey')
    op.create_foreign_key('BetUsers_ibfk_1', 'BetUsers', 'Bets', ['bet_id'], ['id'])
    # ### end Alembic commands ###
