"""empty message

Revision ID: 7e82e3d99e31
Revises: f2c8bed848c1
Create Date: 2017-11-29 21:07:17.783179

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e82e3d99e31'
down_revision = 'f2c8bed848c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Friends')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Friends',
    sa.Column('user_to', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_from', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_from'], ['Users.id'], name='Friends_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_to'], ['Users.id'], name='Friends_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_to', 'user_from'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
