"""empty message

Revision ID: 86bc8cf819c8
Revises: 1b206605542d
Create Date: 2017-11-19 18:04:53.152635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86bc8cf819c8'
down_revision = '1b206605542d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bets', sa.Column('color', sa.Integer(), nullable=True))
    op.add_column('Bets', sa.Column('icon', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bets', 'icon')
    op.drop_column('Bets', 'color')
    # ### end Alembic commands ###
