"""empty message

Revision ID: ac0dda6f8492
Revises: 2aa2b672dd1d
Create Date: 2017-10-30 18:47:03.297643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac0dda6f8492'
down_revision = '2aa2b672dd1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bets', sa.Column('side_a', sa.String(length=60), nullable=False))
    op.add_column('Bets', sa.Column('side_b', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bets', 'side_b')
    op.drop_column('Bets', 'side_a')
    # ### end Alembic commands ###
