"""empty message

Revision ID: ae4f765e3cbd
Revises: 150671bccd67
Create Date: 2017-10-26 14:11:59.376381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae4f765e3cbd'
down_revision = '150671bccd67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bets', sa.Column('complete', sa.Boolean(), nullable=False))
    op.add_column('Bets', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('Bets', sa.Column('winner', sa.Boolean(), nullable=True))
    op.drop_column('Bets', 'text')
    op.drop_column('Bets', 'completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bets', sa.Column('completed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('Bets', sa.Column('text', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('Bets', 'winner')
    op.drop_column('Bets', 'description')
    op.drop_column('Bets', 'complete')
    # ### end Alembic commands ###
