"""empty message

Revision ID: bdaffca64318
Revises: cf139b7879fa
Create Date: 2017-11-02 19:27:41.684261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bdaffca64318'
down_revision = 'cf139b7879fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Transactions_ibfk_3', 'Transactions', type_='foreignkey')
    op.drop_column('Transactions', 'bet_ud')
    op.add_column('Users', sa.Column('current_balance', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'current_balance')
    op.add_column('Transactions', sa.Column('bet_ud', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('Transactions_ibfk_3', 'Transactions', 'Bets', ['bet_ud'], ['id'])
    # ### end Alembic commands ###
