"""empty message

Revision ID: bf7ce860c263
Revises: 0246a6ab8ce7
Create Date: 2017-12-01 01:42:40.736584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7ce860c263'
down_revision = '0246a6ab8ce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Notifications', sa.Column('notif_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Notifications', 'notif_type')
    # ### end Alembic commands ###
