"""empty message

Revision ID: cf139b7879fa
Revises: ac0dda6f8492
Create Date: 2017-10-30 23:17:45.064156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf139b7879fa'
down_revision = 'ac0dda6f8492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BetUsers', sa.Column('side', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('BetUsers', 'side')
    # ### end Alembic commands ###
