"""empty message

Revision ID: ece04bf2e6a3
Revises: 216e7bdd51b1
Create Date: 2017-11-13 13:11:49.763254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece04bf2e6a3'
down_revision = '216e7bdd51b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('device_id', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'Users', ['device_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_column('Users', 'device_id')
    # ### end Alembic commands ###
