"""empty message

Revision ID: f2c8bed848c1
Revises: 704fd8217b00
Create Date: 2017-11-29 15:13:44.657745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2c8bed848c1'
down_revision = '704fd8217b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Friends', 'Users', ['user_to'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Friends', 'Users', ['user_from'], ['id'], ondelete='CASCADE')
    op.drop_column('Friends', 'user_from_id')
    op.drop_column('Friends', 'user_to_id')
    op.drop_constraint('Likes_ibfk_2', 'Likes', type_='foreignkey')
    op.create_foreign_key(None, 'Likes', 'Users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('Transactions_ibfk_1', 'Transactions', type_='foreignkey')
    op.create_foreign_key(None, 'Transactions', 'Users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Transactions', type_='foreignkey')
    op.create_foreign_key('Transactions_ibfk_1', 'Transactions', 'Users', ['user_id'], ['id'])
    op.drop_constraint(None, 'Likes', type_='foreignkey')
    op.create_foreign_key('Likes_ibfk_2', 'Likes', 'Users', ['user_id'], ['id'])
    op.add_column('Friends', sa.Column('user_to_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('Friends', sa.Column('user_from_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Friends', type_='foreignkey')
    op.drop_constraint(None, 'Friends', type_='foreignkey')
    # ### end Alembic commands ###
