"""empty message

Revision ID: fbc74473bbb7
Revises: 05d780eb0301
Create Date: 2017-11-29 14:05:36.317062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc74473bbb7'
down_revision = '05d780eb0301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Likes_ibfk_1', 'Likes', type_='foreignkey')
    op.create_foreign_key(None, 'Likes', 'Bets', ['bet_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Likes', type_='foreignkey')
    op.create_foreign_key('Likes_ibfk_1', 'Likes', 'Bets', ['bet_id'], ['id'])
    # ### end Alembic commands ###
